/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gerenciadorTarefas;

import gerenciadorTarefas.DAO.UsuarioDAO;
import gerenciadorTarefas.model.Usuario;
import gerenciadorTarefas.service.TarefaService;





public class App {

    public static void main(String[] args) {
        
       

}}
